# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-added-large-files" },
  { id = "debug-statements" },
  { id = "destroyed-symlinks" },
  { id = "check-toml" },
  { id = "check-merge-conflict" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.20"
hooks = [
  { id = "ruff", args = [
    "--fix",
  ], language = "system" },
  { id = "ruff-format", language = "system" },
]

[[repos]]
repo = "https://github.com/facebook/pyrefly-pre-commit"
rev = "1.1.1"
hooks = [{ id = "pyrefly-check", pass_filenames = false, language = "system" }]

[[repos]]
repo = "https://github.com/oxc-project/mirrors-oxfmt"
rev = "v0.56.0"
hooks = [{ id = "oxfmt" }]

[[repos]]
repo = "https://github.com/oxc-project/mirrors-oxlint"
rev = "v1.71.0"
hooks = [{ id = "oxlint" }]
