from typing import Any

class JavaScriptError(Exception):
    name: str
    message: str
    stack: str | None

class Runtime:
    def __init__(self) -> None: ...
    def eval(self, source: str) -> Any: ...
    async def eval_async(self, source: str) -> Any: ...
    def close(self) -> None: ...

def v8_version() -> str: ...
def create_snapshot(scripts: list[tuple[str, str]], warmup: str | None = None) -> bytes: ...
