import asyncio
from typing import Any

class JavaScriptError(Exception):
    name: str
    message: str
    stack: str | None

class Runtime:
    # Not set by Rust; page.py's sync Page stashes its driving loop here for Element to read.
    _loop: asyncio.AbstractEventLoop

    def __init__(self, snapshot: bytes, url: str, virtual_servers_json: str = "[]") -> None: ...
    def eval(self, source: str) -> Any: ...
    async def eval_async(self, source: str) -> Any: ...
    def register_function(self, name: str, callable: Any) -> None: ...
    def install_host_ops(
        self,
        fetch: Any,
        fetch_abort: Any,
        fetch_sync: Any,
    ) -> None: ...
    def close(self) -> None: ...

def v8_version() -> str: ...
def create_snapshot(scripts: list[tuple[str, str]]) -> bytes: ...
